### ISSUE TITLE
Add support for starting DSE Graph, Solr, and Spark workloads

### ISSUE THREAD

**Issue by respringer** [datastax/management-api-for-apache-cassandra#32]
We need the ability to start DSE nodes with Graph, Solr, and Spark workloads enabled.  We will need a method of requesting the workloads such as the three existing environment variables:

GRAPH_ENABLED=1
SOLR_ENABLED=1
SPARK_ENABLED=1

**Comment by jimdickinson** [comment]
I think @respringer solved this with the existing management API interfaces and changing the k8s pod spec that the operator creates.
