### ISSUE TITLE
CASSANDRA-15299 breaks UnixSocketServer4x

### ISSUE THREAD

**Issue by jsanda** [datastax/management-api-for-apache-cassandra#58]
[CASSANDRA-15299](https://issues.apache.org/jira/browse/CASSANDRA-15299) has been merged into trunk and will be in the next 4.0-beta4 release. The following classes were removed in that ticket (See this [commit](https://github.com/apache/cassandra/commit/a7c4ba9eeecb365e7c4753d8eaab747edd9a632a):

* `org.apache.cassandra.transport.Message.ProtocolEncoder` 
* `org.apache.cassandra.transport.Message.ProtocolDecoder`

 These classes are used directly in the `org.apache.cassandra.transport.UnixSocketServer4x` class.

This currently is not a problem for the Management API since it is built against 4.0-beta1, but it will break once we try to upgrade the Cassandra 4 dependency to 4.0-beta1 do to the changes in CASSANDRA-15299.

**Comment by emerkle826** [comment]
I'll try to resolve this.

**Comment by emerkle826** [comment]
I've got a preliminary fix for this here:
https://github.com/datastax/management-api-for-apache-cassandra/commit/e59052d9a3908dff1d0ce42a01b00dd7439c449e

**Caveat**
The change in that branch updates the `cassandra-all.jar` dependency to `4.0-beta4-SNAPSHOT`, which is not published as of yet. Once a Beta4 release is published, this dependency should change to simply `4.0-beta4`. If you build the Cassandra artifacts locally, and have the snapshot Beta4 artifact in your local Maven repository, the branch mentioned should build. I have not yet done any extensive testing against the latest C* 4.0 builds as of yet.

**Comment by emerkle826** [comment]
PR for this is #59

**Comment by emerkle826** [comment]
Closing as #59 is merged.
