### ISSUE TITLE
Create image for Cassandra 4.0-beta4

### ISSUE THREAD

**Issue by jsanda** [datastax/management-api-for-apache-cassandra#65]
Cassandra 4.0-beta4 was released on 12/30/2020. It does not look like there are management-api images for any of the recent 4.0 betas. I would like to have a management-api image build for4.0-beta4 for k8ssandra in preparation of the 4.0 GA release.

@emerkle826 can you take this?

**Comment by emerkle826** [comment]
Closing this and #59 is merged.
