### ISSUE TITLE
Solve failing IntegrationTest for Cassandra 4.0-beta4

### ISSUE THREAD

**Issue by scottbale** [datastax/management-api-for-apache-cassandra#67]
The `testSuperuserWasNotSet` test in `IntegrationTest` fails on the `assertTrue(ready)` assert, meaning all of the calls to the readiness probe are failing (each call is returning `500 Internal Server Error`). Only happening for C* 4.0 beta 4. 

Looking at logging, seems the mgmt api server (running inside the container) is logging
```
Internal connection to Cassandra closed
```
which indicates the server can't communicate over the unix socket for some reason TBD.

**Comment by emerkle826** [comment]
The little bit that I tried to debug on this, it seemed like the Unix Socket used by `K8OperatorResources` for the readiness check complained because it couldn't authenticate. Which sorta makes sense since the test in question is trying to enable Cassandra PasswordAuthenticator. However, that test does the same thing for C* 3.11 and DSE 6.8, but in those cases, there is no authentication issue over that Unix socket.

**Comment by emerkle826** [comment]
I think I have a solution, but I'm not 100% confident in it. I noticed that for the 3.x agent, a state transition from UNINITIALIZED to AUTHENTICATION was commented out on receiving a STARTUP message [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/master/management-api-shim-3.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer3x.java#L171-L178)

For the 4.x agent, that bit is not commented out [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/master/management-api-shim-4.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer4x.java#L171-L178).

So I tried bypassing this for the 4.x agent [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/cass4-beta4/management-api-agent-4.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer4x.java#L183-L188). This almost worked, but I had to also catch the AuthenticateMessage and replace with a new ReadyMessage [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/cass4-beta4/management-api-agent-4.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer4x.java#L296-L298).

Those two changes allow the Unix Socket to connect and bypass Authentication. However, the same override is done a little differently in 3.x (and DSE 6.8).

Again, I mention that the state transition just bypassed AUTHENTICATION for 3.x, and went straight to READY. The same is not true for DSE 6.8 [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/master/management-api-shim-dse-6.8/src/main/java/org/apache/cassandra/transport/UnixSocketServerDse68.java#L227-L234), and the test passes for DSE 6.8. I then suspected that we likely don't need to comment things out for 3.x either, so I tried that [here](https://github.com/datastax/management-api-for-apache-cassandra/blob/cass4-beta4/management-api-agent-3.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer3x.java#L171-L178), and it still passes.

What seems to be happening for 3.x and DSE 6.8 is that the [UnixSockMessage](https://github.com/datastax/management-api-for-apache-cassandra/blob/cass4-beta4/management-api-agent-3.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer3x.java#L96-L97) is actually hit for AuthenticateMessages after STARTUP, but for 4.x [the same bit of code](https://github.com/datastax/management-api-for-apache-cassandra/blob/cass4-beta4/management-api-agent-4.x/src/main/java/org/apache/cassandra/transport/UnixSocketServer4x.java#L107-L108) is not hit for AuthenticateMessages. The way I have fixed this in the 4.x agent is to catch the AuthenticateMessage response from dispatching the STARTUP request, and replacing it with a ReadyMessage, resulting in, what I believe is, the same effect as the replacement done in 3.x and DSE 6.8 agents.

What I'm a little perplexed at is that the UnixSockMessage _dispatcher_ doesn't seem to get invoked in the 4.x pipeline when an AuthenticateMessage is the response to a Startup. By overriding the response to Ready, things progress as normal, with the next request coming in as a QueryMessage, and the UnixSockMessage instance handles it as expected.

Perhaps something is not quite right with the Unix socket _client_ with how I've implemented the pipeline changes for C* 4.0?

**Comment by emerkle826** [comment]
After adding some debug logging and comparing between 3.11 and 4.0 for this particular test, I'm more confident what I have is correct. For 3.11, the pipeline dispatcher is essentially the custom UnixSockMessage class. It handles the OPTIONS and STARTUP messages in addition to all the Queries that will follow. Here's a the logging I temporarily added:

```
INFO  [main] 2021-02-05 01:39:56,054 CassandraDaemonInterceptor.java:62 - Starting DataStax Management API Agent for Apache Cassandra v0.1
INFO  [main] 2021-02-05 01:39:56,113 IPCController.java:105 - Starting Server
INFO  [main] 2021-02-05 01:39:56,114 IPCController.java:114 - Started Server
INFO  [main] 2021-02-05 01:39:56,114 CassandraDaemonInterceptor.java:89 - Starting listening for CQL clients on /tmp/cassandra.sock ...
INFO  [main] 2021-02-05 01:39:56,114 CassandraDaemon.java:650 - Startup complete
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,734 UnixSocketServer3x.java:145 - Validating new message in UNINITIALIZED for message type OPTIONS
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,735 UnixSocketServer3x.java:92 - Executing OPTIONS 4/v4 0
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,756 UnixSocketServer3x.java:170 - Applying transition from UNINITIALIZED for Request OPTIONS and Response SUPPORTED
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,762 UnixSocketServer3x.java:145 - Validating new message in UNINITIALIZED for message type STARTUP
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,762 UnixSocketServer3x.java:92 - Executing STARTUP {DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.10.0, CLIENT_ID=b429514d-90c9-4bcc-a667-700a9428d6e6, CQL_VERSION=3.0.0} 4/v4 0
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,772 UnixSocketServer3x.java:170 - Applying transition from UNINITIALIZED for Request STARTUP and Response READY
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,779 UnixSocketServer3x.java:145 - Validating new message in READY for message type QUERY
INFO  [epollEventLoopGroup-4-4] 2021-02-05 01:40:04,779 UnixSocketServer3x.java:92 - Executing QUERY SELECT cluster_name FROM system.local[pageSize = -1] 4/v4 0
```

For 4.0, the new pipeline initialization is a bit different. The UnixSockMessage class doesn't handle the OPTIONS or STARTUP messages, so it never has a chance to bypass the AuthenticateMessage, as I suspected.

```
INFO  [main] 2021-02-05 01:43:38,712 CassandraDaemonInterceptor.java:62 - Starting DataStax Management API Agent for Apache Cassandra v0.1
INFO  [main] 2021-02-05 01:43:38,747 IPCController.java:105 - Starting Server
INFO  [main] 2021-02-05 01:43:38,748 IPCController.java:114 - Started Server
INFO  [main] 2021-02-05 01:43:38,748 CassandraDaemonInterceptor.java:89 - Starting listening for CQL clients on /tmp/cassandra.sock ...
INFO  [main] 2021-02-05 01:43:38,748 CassandraDaemon.java:693 - Startup complete
INFO  [epollEventLoopGroup-7-4] 2021-02-05 01:43:45,157 UnixSocketServer4x.java:157 - Validating new message in UNINITIALIZED for message type STARTUP
INFO  [epollEventLoopGroup-7-4] 2021-02-05 01:43:45,173 UnixSocketServer4x.java:182 - Applying transition from UNINITIALIZED for Request STARTUP and Response AUTHENTICATE
INFO  [epollEventLoopGroup-7-4] 2021-02-05 01:43:45,177 UnixSocketServer4x.java:157 - Validating new message in READY for message type QUERY
INFO  [epollEventLoopGroup-7-4] 2021-02-05 01:43:45,177 UnixSocketServer4x.java:103 - Executing QUERY SELECT cluster_name FROM system.local [pageSize = -1] 4/v4 0
```

The UnixSockMessage _dispatcher_ doesn't get wired in until after the STARTUP request is processed and the AUTHENTICATE response is sent on the channel. So I think I have to do what I did and catch the AUTHENTICATE message in the new pipeline initializer bit, change it to a READY message so that the Unix socket bypasses authentication, and then the UnixSockMessage dispatcher handles things from there.

@scottbale Let me know if you see something wrong with my assumptions, but I think what I have in the PR now should be good (all the tests are passing and none are skipped now).

**Comment by scottbale** [comment]
Awesome! I knew if I dragged my feet long enough that someone else would take care of this :laughing: 

Yeah I'll double check everything. Thanks!

**Comment by emerkle826** [comment]
Thanks again for helping @scottbale . Closing this one as #59 is now merged.
