### ISSUE TITLE
Fix cassandra user's HOME directory

### ISSUE THREAD

**Issue by emerkle826** [datastax/management-api-for-apache-cassandra#88]
See [this issue](https://github.com/k8ssandra/k8ssandra/issues/396)

Essentially, now that Management API runs as the `cassandra` user, that user's effective HOME directory should exist and be writable by that user. We can either:

1) Create the default HOME directory of `/home/cassandra` and set the correct permissions, or
2) Run a `usermod` command to alter the home directory to `/opt/cassandra` which is already setup with correct permissions.

**Comment by careykevin** [comment]
I can work on this - this will be my first issue here.

Creating the default HOME directory of `/home/cassandra` and setting the permissions makes sense to me - that's where I'd expect to find the cqlsh logs given that the user is `cassandra`.
